// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Recipe struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	Description     sql.NullString
	IsPublic        bool
	Ingredients     json.RawMessage
	Nutrition       *json.RawMessage
	Instructions    string
	NutritionStatus string
	DeletedAt       sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	DisplayName    string
	HashedPassword string
	IsPremium      bool
	DeletedAt      sql.NullTime
}
