// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const completeNutritionCalculation = `-- name: CompleteNutritionCalculation :one
UPDATE recipes
SET nutrition = $1,
   nutrition_status = 'completed',
   updated_at = NOW()
WHERE id = $2
   AND deleted_at IS NULL
RETURNING id, user_id, created_at, updated_at, title, description, is_public, ingredients, nutrition, instructions, nutrition_status, deleted_at
`

type CompleteNutritionCalculationParams struct {
	Nutrition *json.RawMessage
	ID        uuid.UUID
}

func (q *Queries) CompleteNutritionCalculation(ctx context.Context, arg CompleteNutritionCalculationParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, completeNutritionCalculation, arg.Nutrition, arg.ID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.IsPublic,
		&i.Ingredients,
		&i.Nutrition,
		&i.Instructions,
		&i.NutritionStatus,
		&i.DeletedAt,
	)
	return i, err
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
   id,
   user_id,
   created_at,
   updated_at,
   title,
   description,
   is_public,
   ingredients,
   instructions
) VALUES (
   $1, $2, NOW(), NOW(), $3, $4, $5, $6, $7
)
RETURNING id, user_id, created_at, updated_at, title, description, is_public, ingredients, nutrition, instructions, nutrition_status, deleted_at
`

type CreateRecipeParams struct {
	ID           uuid.UUID
	UserID       uuid.NullUUID
	Title        string
	Description  sql.NullString
	IsPublic     bool
	Ingredients  json.RawMessage
	Instructions string
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.IsPublic,
		arg.Ingredients,
		arg.Instructions,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.IsPublic,
		&i.Ingredients,
		&i.Nutrition,
		&i.Instructions,
		&i.NutritionStatus,
		&i.DeletedAt,
	)
	return i, err
}

const getAllPublicRecipesByOwnerID = `-- name: GetAllPublicRecipesByOwnerID :many
SELECT id, user_id, created_at, updated_at, title, description, is_public, ingredients, nutrition, instructions, nutrition_status, deleted_at FROM recipes
WHERE user_id = $1
AND is_public IS TRUE
AND deleted_at IS NULL
`

func (q *Queries) GetAllPublicRecipesByOwnerID(ctx context.Context, userID uuid.NullUUID) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getAllPublicRecipesByOwnerID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.IsPublic,
			&i.Ingredients,
			&i.Nutrition,
			&i.Instructions,
			&i.NutritionStatus,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRecipesByOwnerID = `-- name: GetAllRecipesByOwnerID :many
SELECT id, user_id, created_at, updated_at, title, description, is_public, ingredients, nutrition, instructions, nutrition_status, deleted_at FROM recipes
WHERE user_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetAllRecipesByOwnerID(ctx context.Context, userID uuid.NullUUID) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getAllRecipesByOwnerID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.IsPublic,
			&i.Ingredients,
			&i.Nutrition,
			&i.Instructions,
			&i.NutritionStatus,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, user_id, created_at, updated_at, title, description, is_public, ingredients, nutrition, instructions, nutrition_status, deleted_at FROM recipes
WHERE id = $1
AND deleted_at IS NULL
AND (is_public = TRUE OR user_id = $2)
`

type GetRecipeByIDParams struct {
	ID     uuid.UUID
	UserID uuid.NullUUID
}

func (q *Queries) GetRecipeByID(ctx context.Context, arg GetRecipeByIDParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByID, arg.ID, arg.UserID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.IsPublic,
		&i.Ingredients,
		&i.Nutrition,
		&i.Instructions,
		&i.NutritionStatus,
		&i.DeletedAt,
	)
	return i, err
}

const markAllUserRecipesSoftDelete = `-- name: MarkAllUserRecipesSoftDelete :exec
UPDATE recipes
SET deleted_at = NOW()
WHERE user_id = $1
AND deleted_at IS NULL
AND is_public IS FALSE
`

func (q *Queries) MarkAllUserRecipesSoftDelete(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, markAllUserRecipesSoftDelete, userID)
	return err
}

const markRecipeSoftDeleteByID = `-- name: MarkRecipeSoftDeleteByID :exec
UPDATE recipes
SET deleted_at = NOW()
WHERE id = $1
AND user_id = $2
AND deleted_at IS NULL
`

type MarkRecipeSoftDeleteByIDParams struct {
	ID     uuid.UUID
	UserID uuid.NullUUID
}

func (q *Queries) MarkRecipeSoftDeleteByID(ctx context.Context, arg MarkRecipeSoftDeleteByIDParams) error {
	_, err := q.db.ExecContext(ctx, markRecipeSoftDeleteByID, arg.ID, arg.UserID)
	return err
}

const purgeExpiredRecipes = `-- name: PurgeExpiredRecipes :exec
DELETE FROM recipes
WHERE deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) PurgeExpiredRecipes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeExpiredRecipes)
	return err
}

const updateRecipeFull = `-- name: UpdateRecipeFull :one
UPDATE recipes
SET updated_at = NOW(),
   title = $1,
   description = $2,
   is_public = $3,
   ingredients = $4,
   instructions = $5,
   nutrition = NULL,
   nutrition_status = 'unprocessed'
WHERE id = $6
AND user_id = $7
AND deleted_at IS NULL
RETURNING id, user_id, created_at, updated_at, title, description, is_public, ingredients, nutrition, instructions, nutrition_status, deleted_at
`

type UpdateRecipeFullParams struct {
	Title        string
	Description  sql.NullString
	IsPublic     bool
	Ingredients  json.RawMessage
	Instructions string
	ID           uuid.UUID
	UserID       uuid.NullUUID
}

func (q *Queries) UpdateRecipeFull(ctx context.Context, arg UpdateRecipeFullParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipeFull,
		arg.Title,
		arg.Description,
		arg.IsPublic,
		arg.Ingredients,
		arg.Instructions,
		arg.ID,
		arg.UserID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.IsPublic,
		&i.Ingredients,
		&i.Nutrition,
		&i.Instructions,
		&i.NutritionStatus,
		&i.DeletedAt,
	)
	return i, err
}

const updateRecipeVisibility = `-- name: UpdateRecipeVisibility :one
UPDATE recipes
SET is_public = $1
WHERE user_id = $2
AND id = $3
AND deleted_at IS NULL
RETURNING id, user_id, created_at, updated_at, title, description, is_public, ingredients, nutrition, instructions, nutrition_status, deleted_at
`

type UpdateRecipeVisibilityParams struct {
	IsPublic bool
	UserID   uuid.NullUUID
	ID       uuid.UUID
}

func (q *Queries) UpdateRecipeVisibility(ctx context.Context, arg UpdateRecipeVisibilityParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipeVisibility, arg.IsPublic, arg.UserID, arg.ID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.IsPublic,
		&i.Ingredients,
		&i.Nutrition,
		&i.Instructions,
		&i.NutritionStatus,
		&i.DeletedAt,
	)
	return i, err
}
