// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
   id,
   created_at,
   updated_at,
   email,
   display_name,
   hashed_password,
   is_premium
) VALUES (
   $1, NOW(), NOW(), $2, $3, $4, $5
)
RETURNING id, created_at, updated_at, email, display_name, is_premium
`

type CreateUserParams struct {
	ID             uuid.UUID
	Email          string
	DisplayName    string
	HashedPassword string
	IsPremium      bool
}

type CreateUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	DisplayName string
	IsPremium   bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.HashedPassword,
		arg.IsPremium,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
		&i.IsPremium,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, display_name, hashed_password, is_premium FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
		&i.HashedPassword,
		&i.IsPremium,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, email, display_name, is_premium
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	DisplayName string
	IsPremium   bool
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
		&i.IsPremium,
	)
	return i, err
}

const updateUserFull = `-- name: UpdateUserFull :one
UPDATE users
SET display_name = $1,
   email = $2,
   hashed_password = $3,
   updated_at = NOW()
WHERE id = $4
RETURNING id, created_at, updated_at, display_name, email, is_premium
`

type UpdateUserFullParams struct {
	DisplayName    string
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

type UpdateUserFullRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DisplayName string
	Email       string
	IsPremium   bool
}

func (q *Queries) UpdateUserFull(ctx context.Context, arg UpdateUserFullParams) (UpdateUserFullRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserFull,
		arg.DisplayName,
		arg.Email,
		arg.HashedPassword,
		arg.ID,
	)
	var i UpdateUserFullRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Email,
		&i.IsPremium,
	)
	return i, err
}

const updateUserPartial = `-- name: UpdateUserPartial :one
UPDATE users
SET display_name = COALESCE($1, display_name),
   email = COALESCE($2, email),
   hashed_password = COALESCE($3, hashed_password),
   updated_at = NOW()
WHERE id = $4
RETURNING id, created_at, updated_at, display_name, email, is_premium
`

type UpdateUserPartialParams struct {
	DisplayName    sql.NullString
	Email          sql.NullString
	HashedPassword sql.NullString
	ID             uuid.UUID
}

type UpdateUserPartialRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DisplayName string
	Email       string
	IsPremium   bool
}

func (q *Queries) UpdateUserPartial(ctx context.Context, arg UpdateUserPartialParams) (UpdateUserPartialRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserPartial,
		arg.DisplayName,
		arg.Email,
		arg.HashedPassword,
		arg.ID,
	)
	var i UpdateUserPartialRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Email,
		&i.IsPremium,
	)
	return i, err
}
